version: 2

.defaults: &defaults
  docker:
    - image: circleci/node:12-stretch
  working_directory: ~/projects/eorzea-weather

.attach_workspace: &attach_workspace
  attach_workspace:
    at: ~/projects

.install_steps: &install_steps
  steps:
    - checkout
    - *attach_workspace
    - restore_cache:
        keys:
          - v1-node-dependencies-{{ checksum "yarn.lock" }}
          - v1-node-dependencies-
    - run: yarn install --frozen-lockfile
    - save_cache:
        key: v1-node-dependencies-{{ checksum "yarn.lock" }}
        paths:
          - ./node_modules/
    - persist_to_workspace:
        root: ~/projects
        paths:
          - eorzea-weather

.test_steps: &test_steps
  steps:
    - *attach_workspace
    - run: yarn test

jobs:
  install:
    <<: *defaults
    <<: *install_steps
  lint:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: yarn lint
    <<: *test_steps
  test-node10:
    <<: *defaults
    docker:
      - image: circleci/node:10-stretch
    <<: *test_steps
  test-node12:
    <<: *defaults
    docker:
      - image: circleci/node:12-stretch
    <<: *test_steps
  test-node13:
    <<: *defaults
    docker:
      - image: circleci/node:13-stretch
    <<: *test_steps

workflows:
  version: 2
  tests:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test-node10:
          requires:
            - lint
      - test-node12:
          requires:
            - lint
      - test-node13:
          requires:
            - lint
